from gyb_resources_assets import _assets_folder_name
from gyb_resources_assets import image_resources
from gyb_resources_assets import color_resources
from gyb_resources_strings import string_resources
